/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admredes;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo R. Ibarra
 */
public class Oficina1 extends javax.swing.JFrame {

    /**
     * Creates new form Oficina1
     */
    public Oficina1() {
        initComponents();
        this.setLocationRelativeTo(null);
        JPanelImage mImage = new JPanelImage(PanelOf1, "src/imagenes/oficinas.png");
        PanelOf1.add(mImage).repaint();
        PanelOf1.setOpaque(false);
        PanelOf1.setBorder(null);
        PanelOf1.setBackground(new  Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOf1 = new javax.swing.JPanel();
        bOf1 = new javax.swing.JButton();
        bOf2 = new javax.swing.JButton();
        bOf3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanelOf1Layout = new javax.swing.GroupLayout(PanelOf1);
        PanelOf1.setLayout(PanelOf1Layout);
        PanelOf1Layout.setHorizontalGroup(
            PanelOf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        PanelOf1Layout.setVerticalGroup(
            PanelOf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        bOf1.setText("Oficina 1");
        bOf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOf1ActionPerformed(evt);
            }
        });

        bOf2.setText("Oficina 2");
        bOf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOf2ActionPerformed(evt);
            }
        });

        bOf3.setText("Oficina 3");
        bOf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOf3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOf1)
                        .addGap(18, 18, 18)
                        .addComponent(bOf2)
                        .addGap(18, 18, 18)
                        .addComponent(bOf3))
                    .addComponent(PanelOf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOf1)
                    .addComponent(bOf2)
                    .addComponent(bOf3))
                .addGap(18, 18, 18)
                .addComponent(PanelOf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOf1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Fabricante: Dell"
                + "\nModelo: Optiplex 7010"
                + "\nEstado: Buen estado"
                + "\nUbicación: Sala cómputo 1"
                + "\nDirección IP: 192.168.10.109/24");
    }//GEN-LAST:event_bOf1ActionPerformed

    private void bOf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOf2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Fabricante: Dell"
                + "\nModelo: Optiplex 7010"
                + "\nEstado: Buen estado"
                + "\nUbicación: Sala cómputo 1"
                + "\nDirección IP: 192.168.10.110/24");
                                   
    }//GEN-LAST:event_bOf2ActionPerformed

    private void bOf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOf3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Fabricante: Dell"
                + "\nModelo: Optiplex 7010"
                + "\nEstado: Buen estado"
                + "\nUbicación: Sala cómputo 1"
                + "\nDirección IP: 192.168.10.111/24");                                   
    }//GEN-LAST:event_bOf3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oficina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oficina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oficina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oficina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oficina1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOf1;
    private javax.swing.JButton bOf1;
    private javax.swing.JButton bOf2;
    private javax.swing.JButton bOf3;
    // End of variables declaration//GEN-END:variables

}